name: 自动编译发布

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整历史记录以便获取提交信息
    
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        # 检查requirements.txt是否存在
        if (Test-Path "requirements.txt") {
          pip install -r requirements.txt
        } else {
          # 如果没有requirements.txt，安装基本依赖
          pip install customtkinter requests beautifulsoup4 tqdm stem fake-useragent pycryptodome ebooklib lxml
        }
    
    - name: 编译exe文件
      run: |
        # 设置控制台编码为UTF-8
        [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
        $env:PYTHONIOENCODING = "utf-8"

        # 编译调试版本（带控制台窗口）
        echo "编译调试版本（带控制台窗口）..."
        pyinstaller build_console.spec --clean
    
    - name: 生成版本号和发布信息
      id: release_info
      run: |
        # 生成基于日期的版本号
        $version = "v$(Get-Date -Format 'yyyy.MM.dd.HHmm')"
        echo "version=$version" >> $env:GITHUB_OUTPUT
        
        # 获取最近20次提交信息
        $commits = git log --oneline -20 --pretty=format:"- %s (%an)"
        $release_body = @"
        ## 🚀 自动发布版本 $version
        
        ### 📅 发布时间
        $(Get-Date -Format 'yyyy年MM月dd日 HH:mm:ss')
        
        ### 📝 更新内容（最近20次提交）
        $commits
        
        ### 💾 下载说明

        #### 📦 版本说明：
        - **番茄小说下载器_调试版.exe** - 带控制台窗口版本，便于查看运行信息和调试

        #### 🚀 使用方法：
        - 下载exe文件
        - 双击运行即可使用，无需安装Python环境
        - 支持Windows 10及以上系统
        - 控制台窗口会显示详细的运行信息

        ### ⚠️ 注意事项
        - 首次运行可能被杀毒软件误报，请添加信任
        - 控制台窗口会显示详细的下载进度和错误信息
        - 如有问题请在Issues中反馈
        "@
        
        # 将发布内容写入文件
        $release_body | Out-File -FilePath release_body.txt -Encoding UTF8
        echo "release_body_file=release_body.txt" >> $env:GITHUB_OUTPUT
    
    - name: 检查文件是否存在
      run: |
        $file = "dist/番茄小说下载器_调试版.exe"

        if (Test-Path $file) {
          $size = (Get-Item $file).Length / 1MB
          $fileName = Split-Path $file -Leaf
          echo "✅ $fileName 编译成功 - 大小: $([math]::Round($size, 2)) MB"
        } else {
          echo "❌ $file 编译失败"
          exit 1
        }
    
    - name: 创建Release并上传文件
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.release_info.outputs.version }}
        name: 番茄小说下载器 ${{ steps.release_info.outputs.version }}
        body_path: ${{ steps.release_info.outputs.release_body_file }}
        files: |
          dist/番茄小说下载器_调试版.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: 发布完成通知
      run: |
        echo "🎉 发布完成！"
        echo "📦 版本号: ${{ steps.release_info.outputs.version }}"
        echo "🔗 下载链接: https://github.com/${{ github.repository }}/releases/tag/${{ steps.release_info.outputs.version }}"
