name: 多平台编译并发布
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows
            arch: x64
            executable_ext: .exe
          - os: ubuntu-latest
            platform: linux
            arch: x64
            executable_ext: ""
          - os: macos-latest
            platform: macos
            arch: x64
            executable_ext: ""
          - os: macos-14  # Apple Silicon
            platform: macos
            arch: arm64
            executable_ext: ""
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 20
        
    - name: 设置Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: 安装依赖 (Windows)
      if: matrix.platform == 'windows'
      shell: pwsh
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        
        $packages = @(
          "customtkinter>=5.2.0",
          "requests>=2.31.0",
          "beautifulsoup4>=4.12.0",
          "tqdm>=4.65.0",
          "stem>=1.8.0",
          "fake-useragent>=1.4.0",
          "pycryptodome>=3.18.0",
          "ebooklib>=0.18",
          "lxml>=4.9.0",
          "urllib3>=2.0.0",
          "PySocks>=1.7.1"
        )
        
        foreach ($package in $packages) {
          pip install $package
        }
        
    - name: 安装依赖 (Unix系统)
      if: matrix.platform != 'windows'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        
        packages=(
          "customtkinter>=5.2.0"
          "requests>=2.31.0"
          "beautifulsoup4>=4.12.0"
          "tqdm>=4.65.0"
          "stem>=1.8.0"
          "fake-useragent>=1.4.0"
          "pycryptodome>=3.18.0"
          "ebooklib>=0.18"
          "lxml>=4.9.0"
          "urllib3>=2.0.0"
          "PySocks>=1.7.1"
        )
        
        for package in "${packages[@]}"; do
          pip install "$package"
        done
        
    - name: 验证PyInstaller配置文件
      shell: bash
      run: |
        if [ -f "build_console.spec" ]; then
          echo "✅ build_console.spec 文件存在"
          head -10 build_console.spec || true
        else
          echo "❌ build_console.spec 文件不存在"
          exit 1
        fi
        
    - name: 编译可执行文件
      shell: bash
      run: |
        pyinstaller build_console.spec --clean --noconfirm
        
    - name: 重命名可执行文件
      shell: bash
      run: |
        if [ "${{ matrix.platform }}" = "windows" ]; then
          if [ -f "dist/FanqieDownloader_Debug.exe" ]; then
            mv "dist/FanqieDownloader_Debug.exe" "dist/FanqieDownloader_Debug_windows_${{ matrix.arch }}.exe"
          fi
        else
          if [ -f "dist/FanqieDownloader_Debug" ]; then
            mv "dist/FanqieDownloader_Debug" "dist/FanqieDownloader_Debug_${{ matrix.platform }}_${{ matrix.arch }}"
            chmod +x "dist/FanqieDownloader_Debug_${{ matrix.platform }}_${{ matrix.arch }}"
          fi
        fi
        
    - name: 列出编译结果
      shell: bash
      run: |
        ls -la dist/
        
    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: fanqie-downloader-${{ matrix.platform }}-${{ matrix.arch }}
        path: |
          dist/FanqieDownloader_Debug_*
        retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 20
        
    - name: 下载所有构建产物
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        
    - name: 整理发布文件
      run: |
        mkdir -p release_files
        find artifacts -name "FanqieDownloader_Debug_*" -type f -exec cp {} release_files/ \;
        ls -la release_files/
        
    - name: 生成版本信息
      id: version
      env:
        TZ: 'Asia/Shanghai'
      run: |
        version="v$(date +'%Y.%m.%d.%H%M')"
        echo "tag=$version" >> $GITHUB_OUTPUT
        git log --oneline -20 --pretty=format:"- %s" > commits.txt
        
    - name: 创建发布说明文件
      env:
        TZ: 'Asia/Shanghai'
      run: |
        version="${{ steps.version.outputs.tag }}"
        current_time=$(date +'%Y-%m-%d %H:%M:%S CST')
        commit_content=$(cat commits.txt)
        
        cat > release_notes.md << EOF
        ## Fanqie Novel Downloader $version
        
        ### 发布时间 / Release Time
        $current_time (中国标准时间)
        
        ### 更新内容 / Updates
        $commit_content
        
        ### 平台支持 / Platform Support
        此版本支持以下平台：
        
        #### Windows
        - **FanqieDownloader_Debug_windows_x64.exe** - Windows 10+ (64位)
        
        #### Linux
        - **FanqieDownloader_Debug_linux_x64** - Linux (64位)
        
        #### macOS
        - **FanqieDownloader_Debug_macos_x64** - macOS Intel (64位)
        - **FanqieDownloader_Debug_macos_arm64** - macOS Apple Silicon (M1/M2)
        
        ### 使用说明 / Usage Instructions
        
        #### Windows 用户：
        1. 下载 .exe 文件
        2. 双击运行
        3. 首次运行可能被杀毒软件拦截，请添加信任
        
        #### Linux 用户：
        1. 下载对应的二进制文件
        2. 添加执行权限：\`chmod +x FanqieDownloader_Debug_linux_x64\`
        3. 运行：\`./FanqieDownloader_Debug_linux_x64\`
        
        #### macOS 用户：
        1. 下载对应版本（Intel Mac 选择 x64，Apple Silicon 选择 arm64）
        2. 添加执行权限：\`chmod +x FanqieDownloader_Debug_macos_*\`
        3. 运行：\`./FanqieDownloader_Debug_macos_*\`
        4. 如被系统阻止，请在系统偏好设置 > 安全性与隐私中允许运行
        
        ### 注意事项 / Notes
        - 控制台窗口会显示详细的下载进度和错误信息
        - 如遇问题请在 Issues 中反馈
        - 所有二进制文件都是独立运行的，无需安装 Python
        EOF
        
    - name: 创建Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.tag }}
        name: Fanqie Novel Downloader ${{ steps.version.outputs.tag }}
        body_path: release_notes.md
        files: |
          release_files/*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
