name: 编译并发布exe

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 20  # 获取最近20次提交
    
    - name: 设置Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: 安装依赖
      shell: pwsh
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        
        # 安装项目依赖
        $packages = @(
          "customtkinter>=5.2.0",
          "requests>=2.31.0",
          "beautifulsoup4>=4.12.0",
          "tqdm>=4.65.0",
          "stem>=1.8.0",
          "fake-useragent>=1.4.0",
          "pycryptodome>=3.18.0",
          "ebooklib>=0.18",
          "lxml>=4.9.0",
          "urllib3>=2.0.0",
          "PySocks>=1.7.1"
        )
        
        foreach ($package in $packages) {
          pip install $package
        }
    
    - name: 验证PyInstaller配置文件
      shell: pwsh
      run: |
        # 检查build_console.spec文件是否存在
        if (Test-Path "build_console.spec") {
          echo "✅ build_console.spec 文件存在"
          Get-Content "build_console.spec" | Select-Object -First 10
        } else {
          echo "❌ build_console.spec 文件不存在"
          exit 1
        }
    
    - name: 编译exe
      shell: pwsh
      run: |
        # 编译调试版本（带控制台窗口）
        pyinstaller build_console.spec --clean --noconfirm
    
    - name: 生成版本信息
      id: version
      shell: pwsh
      run: |
        $version = "v$(Get-Date -Format 'yyyy.MM.dd.HHmm')"
        echo "tag=$version" >> $env:GITHUB_OUTPUT
        
        # 获取提交信息
        $commits = git log --oneline -20 --pretty=format:"- %s"
        $releaseTime = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
        $body = @"
## 番茄小说下载器 $version

### 发布时间
$releaseTime

### 更新内容
$commits

### 使用说明

#### 版本说明：
- **番茄小说下载器_调试版.exe** - 带控制台窗口版本，便于查看运行信息和调试

#### 使用方法：
1. 下载exe文件
2. 双击运行即可使用
3. 支持 Windows 10+ 系统
4. 控制台窗口会显示详细的运行信息

### 注意事项
- 首次运行可能被杀毒软件拦截，请添加信任
- 控制台窗口会显示详细的下载进度和错误信息
- 如有问题请在 Issues 中反馈
"@
        
        $body | Out-File -FilePath "release_notes.md" -Encoding UTF8
    
    - name: 创建Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.tag }}
        name: 番茄小说下载器 ${{ steps.version.outputs.tag }}
        body_path: release_notes.md
        files: |
          dist/番茄小说下载器_调试版.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
