name: 构建和发布

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            artifact_name: windows
            executable: TomatoNovelDownloader.exe
          - os: ubuntu-latest
            artifact_name: linux
            executable: TomatoNovelDownloader
          - os: macos-latest
            artifact_name: macos
            executable: TomatoNovelDownloader
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置Python环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: 生成版本号并更新version.py
      id: version
      shell: bash
      run: |
        VERSION=$(python -c "import datetime; print(datetime.datetime.now().strftime('%Y.%m.%d.%H%M'))")-$(echo ${{ github.sha }} | cut -c1-7)
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Generated version: $VERSION"
        
        # 生成构建时间
        BUILD_TIME=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')
        echo "BUILD_TIME=$BUILD_TIME" >> $GITHUB_OUTPUT
        echo "Build time: $BUILD_TIME"
        
        # 更新version.py文件
        cat > version.py << EOF
# -*- coding: utf-8 -*-
"""
版本信息文件
"""

__version__ = "$VERSION"
__author__ = "Tomato Novel Downloader"
__description__ = "A modern novel downloader with GitHub auto-update support"
__github_repo__ = "POf-L/Fanqie-novel-Downloader"
EOF
        
        echo "Updated version.py with version: $VERSION"
        cat version.py

    - name: 安装系统依赖 (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk tk-dev

    - name: 安装系统依赖 (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install tcl-tk || true

    - name: 安装系统依赖 (Windows)
      if: runner.os == 'Windows'
      run: |
        # 设置UTF-8编码环境变量
        echo "PYTHONIOENCODING=utf-8" >> $env:GITHUB_ENV
        echo "PYTHONUTF8=1" >> $env:GITHUB_ENV
        # Windows通常自带tkinter，但确保PyInstaller能找到必要的DLL
        echo "Windows系统依赖检查完成"

    - name: 缓存Python依赖
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: 升级pip
      run: |
        python -m pip install --upgrade pip

    - name: 安装依赖
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: 验证依赖安装
      env:
        PYTHONIOENCODING: utf-8
        PYTHONUTF8: 1
      run: |
        python -c "import requests, PIL, ebooklib, bs4, fake_useragent, tqdm; print('All dependencies installed successfully')"

    - name: 检查构建脚本
      run: |
        if [ -f "build_app.py" ]; then
          echo "Found build script build_app.py"
        else
          echo "Build script not found, using default PyInstaller command"
        fi
      shell: bash

    - name: 构建应用
      env:
        PYTHONIOENCODING: utf-8
        PYTHONUTF8: 1
      run: |
        if [ -f "build_app.py" ]; then
          python build_app.py
        else
          # 默认构建命令
          if [ -f "gui.py" ]; then
            pyinstaller --onefile --windowed --name=TomatoNovelDownloader gui.py
          elif [ -f "main.py" ]; then
            pyinstaller --onefile --name=TomatoNovelDownloader main.py
          else
            echo "未找到主程序文件"
            exit 1
          fi
        fi
      shell: bash

    - name: 验证构建结果
      run: |
        if [ -f "dist/${{ matrix.executable }}" ]; then
          echo "Build successful: dist/${{ matrix.executable }}"
          ls -la dist/
        else
          echo "Build failed, executable not found"
          ls -la dist/ || echo "dist directory does not exist"
          exit 1
        fi
      shell: bash

    - name: 创建发布包
      run: |
        mkdir -p release
        cp "dist/${{ matrix.executable }}" "release/"
        
        # 创建压缩包
        cd release
        if [ "${{ runner.os }}" = "Windows" ]; then
          7z a "../TomatoNovelDownloader-${{ steps.version.outputs.VERSION }}-${{ matrix.artifact_name }}.zip" .
        else
          zip -r "../TomatoNovelDownloader-${{ steps.version.outputs.VERSION }}-${{ matrix.artifact_name }}.zip" .
        fi
        cd ..
        
        # 不再需要创建更新信息文件（已移除自动更新功能）
      shell: bash

    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: TomatoNovelDownloader-${{ steps.version.outputs.VERSION }}-${{ matrix.artifact_name }}
        path: |
          TomatoNovelDownloader-${{ steps.version.outputs.VERSION }}-${{ matrix.artifact_name }}.zip
        
  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    permissions:
      contents: write
    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 下载所有构建产物
      uses: actions/download-artifact@v4
      with:
        path: artifacts/

    - name: 获取版本号和构建时间
      id: get_version
      run: |
        # 从文件名中提取版本号
        VERSION=$(find artifacts -name "TomatoNovelDownloader-*" -type d | head -1 | sed 's/.*TomatoNovelDownloader-\(.*\)-.*/\1/')
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Found version: $VERSION"
        
        # 生成构建时间（中国时区）
        BUILD_TIME=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')
        echo "BUILD_TIME=$BUILD_TIME" >> $GITHUB_OUTPUT
        echo "Build time: $BUILD_TIME"

    - name: 整理发布文件
      run: |
        mkdir -p release
        find artifacts -name "*.zip" -exec cp {} release/ \;
        ls -la release/

    - name: 创建Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.get_version.outputs.VERSION }}
        name: TomatoNovelDownloader v${{ steps.get_version.outputs.VERSION }}
        body: |
          ## 🚀 自动构建版本 ${{ steps.get_version.outputs.VERSION }}

          **构建信息:**
          - 构建时间: ${{ steps.get_version.outputs.BUILD_TIME }} (UTC+8)
          - 提交哈希: ${{ github.sha }}
          - 分支: ${{ github.ref_name }}

          **下载说明:**
          - Windows: `TomatoNovelDownloader-${{ steps.get_version.outputs.VERSION }}-windows.zip`
          - Linux: `TomatoNovelDownloader-${{ steps.get_version.outputs.VERSION }}-linux.zip`
          - macOS: `TomatoNovelDownloader-${{ steps.get_version.outputs.VERSION }}-macos.zip`

          **更新内容:**
          ${{ github.event.head_commit.message }}

        files: release/*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}