name: Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: npm install

      - name: Generate Version
        id: generate_version
        run: echo "version_number=1.0.$((Get-Date).ToUnixTimeSeconds())" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Update package.json Version
        run: npm version ${{ steps.generate_version.outputs.version_number }} --no-git-tag-version

      - name: Build and Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run dist